# =============================================================================
# SPLAT CONFIGURATION PROFILE - XENOBLADE CHRONICLES 2 DECOMPILATION
# BUILD ID: A75512BE30BB2A8C880177505D7A0B3E (Segmento main)
# =============================================================================
options:
  platform: switch
  architecture: aarch64
  compiler: clang
  base_path: ..
  target_path: baserom/main.elf
  basename: main
  asm_path: asm
  src_path: src
  build_path: build
  extensions_path: tools
  symbol_map_path: symbols.txt
  mips_to_c_path: tools/mips_to_c
  generate_asm_dependencies: true

segments:
  - name: header
    type: header
    start: 0x0

  - name: segment_0.1
    type: data
    start: 0x100000

  - name: .init
    type: code
    start: 0x100024

  - name: .fini
    type: code
    start: 0x100160

  - name: .text
    type: code
    start: 0x100194
    vram: 0x00100194

  - name: .plt
    type: code
    start: 0x9b2170

  - name: segment_1.1
    type: data
    start: 0x9b4000

  - name: .rela.dyn
    type: data
    start: 0x9b4048

  - name: .rela.plt
    type: data
    start: 0xa70a78

  - name: .hash
    type: data
    start: 0xa72da0

  - name: .gnu.hash
    type: data
    start: 0xa73880

  - name: .dynsym
    type: data
    start: 0xa73938

  - name: .dynstr
    type: data
    start: 0xa76188

  - name: .rodata
    type: rodata
    start: 0xa7a997

  - name: .eh_frame_hdr
    type: rodata
    start: 0xad82f0

  - name: .eh_frame
    type: rodata
    start: 0xb1d910

  - name: .note
    type: data
    start: 0xc38c74

  - name: segment_1.14
    type: data
    start: 0xc38c94

  - name: .data
    type: data
    start: 0xc39000

  - name: .dynamic
    type: data
    start: 0xb81590

  - name: .got.plt
    type: data
    start: 0xc81740

  - name: .got
    type: data
    start: 0xc82310

  - name: segment_2.6
    type: data
    start: 0xc8d8a8

  - name: .init_array
    type: data
    start: 0xc8e758

  - name: .bss
    type: bss
    start: 0xc8ed98  