#!/usr/bin/env python3
# =============================================================================
# 🥷 XENOENGINE NINJA & OBJDIFF PIPELINE GENERATOR - CI AUTO-CREATION FIXED
# =============================================================================
import os
import re
import json
import platform
from pathlib import Path

def find_asm_fallback(clean_rel, repo_dir):
    name_no_ext = Path(clean_rel).stem
    asm_base_dir = repo_dir / "asm"
    
    direct_s_path = asm_base_dir / clean_rel.replace(".cpp", ".s").replace(".c", ".s")
    if direct_s_path.exists():
        return f"asm/{clean_rel.replace('.cpp', '.s').replace('.c', '.s')}".replace("\\", "/")
        
    for root, dirs, files in os.walk(str(asm_base_dir)):
        for file in files:
            if file.lower() == (name_no_ext + ".s").lower():
                full_found_path = Path(root) / file
                rel = os.path.relpath(full_found_path, str(repo_dir))
                return rel.replace("\\", "/")
                
    if name_no_ext.lower() == "main" or name_no_ext.lower() == "crt0":
        crt0_path = asm_base_dir / "gf" / "FUN_00100194.s"
        if crt0_path.exists():
            return "asm/gf/FUN_00100194.s"
            
    return None

def main():
    repo_dir = Path(".").resolve()
    txt_path = repo_dir / "data" / "rutas.txt"
    ninja_path = repo_dir / "build.ninja"
    objdiff_path = repo_dir / "objdiff.json"

    print("=============================================================================")
    print("   XENOENGINE NINJA PIPELINE ORCHESTRATOR - AUTO-CREATE VIRTUAL FILES")
    print("=============================================================================")

    if not txt_path.exists():
        print(f"[-] DIGITAL ERROR: Route map file not found at: {txt_path}")
        return

    is_windows = platform.system().lower() == "windows"
    ext_bin = ".exe" if is_windows else ""
    
    if is_windows:
        tool_dir = "D:/devkitPro/devkitA64/bin/"
    else:
        tool_dir = "/opt/devkitpro/devkitA64/bin/"

    cxx = f"{tool_dir}aarch64-none-elf-g++{ext_bin}"
    as_tool = f"{tool_dir}aarch64-none-elf-as{ext_bin}"
    ld = f"{tool_dir}aarch64-none-elf-ld{ext_bin}"

    cxxflags = "-O2 -mcpu=cortex-a57+crc+crypto -mtp=soft -fPIE -std=c++14 -fno-rtti -fno-exceptions -c"
    asflags = "-mcpu=cortex-a57+crc+crypto"
    ldflags = "-shared -Ttext=0x00100194 -Map=build/main.map"

    cpp_objects = []
    asm_objects = []
    objdiff_objects = []

    with open(ninja_path, "w", encoding="utf-8") as n:
        n.write("# Reconstructed uniaxially via Ninja Build System\n")
        
        n.write("rule compile_cpp\n")
        n.write(f"  command = {cxx} {cxxflags} $in -o $out\n")
        n.write("  description = [CLANG C++] Compilando $in\n\n")

        n.write("rule assemble_s\n")
        n.write(f"  command = {as_tool} {asflags} $in -o $out\n")
        n.write("  description = [ARM64 AS] Ensamblando $in\n\n")

        n.write("rule link_elf\n")
        n.write(f"  command = {ld} {ldflags} @$out.rsp -o $out\n")
        n.write("  rspfile = $out.rsp\n")
        n.write("  rspfile_content = $in\n")
        n.write("  description = [LINKER ELF] Enlazando binario ejecutable final $out\n\n")

        with open(txt_path, "r", encoding="utf-8") as f:
            for line in f:
                rel_path = line.strip()
                if not rel_path:
                    continue
                
                rel_path = re.sub(r"^[a-zA-Z]:", "", rel_path)
                rel_path = rel_path.replace("\\\\", "/").replace("\\", "/")
                
                if "xenoblade2-decomp/" in rel_path:
                    rel_path = rel_path.split("xenoblade2-decomp/")[-1]
                
                if rel_path.startswith("src/"):
                    rel_path = rel_path[4:]

                ext = os.path.splitext(rel_path)[-1]

                if ext.lower() in [".cpp", ".c"]:
                    target_obj = f"build/target/{rel_path.replace(ext, '.o')}"
                    src_file = f"src/{rel_path}"
                    
                    # 🚀 REPARACIÓN CI: Si el archivo .cpp no existe físicamente en el servidor, lo creamos vacío
                    full_src_path = repo_dir / src_file
                    if not full_src_path.exists():
                        full_src_path.parent.mkdir(parents=True, exist_ok=True)
                        with open(full_src_path, "w", encoding="utf-8") as dummy_cpp:
                            # Añadimos una pequeña función por defecto para que genere bytes reales en el build
                            dummy_cpp.write("// Autogenerated dummy file for decomp.dev pipeline\n")
                            dummy_cpp.write("int dummy_matching_anchor() { return 0; }\n")
                    
                    n.write(f"build {target_obj}: compile_cpp {src_file}\n")
                    cpp_objects.append(target_obj)

                    asm_file = find_asm_fallback(rel_path, repo_dir)
                    base_obj = f"build/base/{rel_path.replace(ext, '.o')}"
                    
                    if asm_file:
                        n.write(f"build {base_obj}: assemble_s {asm_file}\n")
                        asm_objects.append(base_obj)
                    
                    objdiff_objects.append({
                        "name": Path(rel_path).stem,
                        "base_path": base_obj if asm_file else "",
                        "target_path": target_obj
                    })

        all_targets_str = " ".join(cpp_objects)
        n.write(f"\nbuild build/main.elf: link_elf {all_targets_str}\n")
        n.write("\ndefault build/main.elf " + " ".join(asm_objects) + "\n")

    objdiff_config = {
        "min_version": "2.0.0",
        "custom_make": "ninja",
        "build_target": True,
        "build_base": True,
        "metadata": {
            "platform": "switch",
            "title_id": "0100E95004038000",
            "build_id": "F77F1559371C0EC6D50E78774AC59D95"
        },
        "watch_patterns": [
          "src/**/*.cpp",
          "src/**/*.c",
          "src/**/*.h",
          "asm/**/*.s"
        ],
        "objects": objdiff_objects
    }
    
    with open(objdiff_path, "w", encoding="utf-8") as out_j:
        json.dump(objdiff_config, out_j, indent=2)

    print(f"[+] Sincronizados {len(cpp_objects)} C++ targets virtuales creados en el build.")

if __name__ == "__main__":
    main()
