#!/usr/bin/env python3
import os
import csv
import re
from pathlib import Path
from capstone import *
from elftools.elf.elffile import ELFFile

def sanitize_filename(name):
    return re.sub(r'[<>:"/\\|?*]', '_', name)

def main():
    repo_dir = Path(__file__).parent.resolve().parent
    elf_path = repo_dir / "baserom" / "main.elf"
    csv_path = repo_dir / "baserom" / "ghidra_export.csv"
    asm_base_dir = repo_dir / "asm"
    symbols_path = repo_dir / "symbols.txt"

    print("=============================================================================")
    print("  XENOENGINE LIVE JIT DISASSEMBLER - ATOMIC SIZE-BASED EXTRACTION")
    print("=============================================================================")

    if not elf_path.exists() or not csv_path.exists():
        print("[-] ERROR: Faltan archivos en baserom/")
        return

    cs = Cs(CS_ARCH_ARM64, CS_MODE_ARM)

    with open(elf_path, "rb") as f:
        elffile = ELFFile(f)
        text_section = elffile.get_section_by_name('.text')
        if not text_section:
            print("[-] ERROR CRÍTICO: No existe la sección .text en el ELF")
            return
        text_data = text_section.data()
        text_vaddr = text_section['sh_addr']

    # 🎯 ANCLAJE QUIRÚRGICO DE TU NUEVA CAPTURA VERIFICADA
    # La función 'init_menu_bdat_subsystem' está en 0x3227b8 y sus bytes coinciden con el offset real
    target_signature = b'\xff\x43\x02\xd1\xf6\x57\x05\xa9' # sub sp, sp, #0x90 ; stp x22, x21...
    signature_vram_anchor = 0x3227b8

    print("[+] Sincronizando el radar molecular con la cota init_menu_bdat_subsystem...")
    offset_in_text_anchor = text_data.find(target_signature)
    
    if offset_in_text_anchor == -1:
        # Fallback de seguridad si los primeros bytes cambian por optimización de registro
        offset_in_text_anchor = 0x3227b8 - text_vaddr
        real_text_vaddr_delta = text_vaddr
    else:
        real_text_vaddr_delta = signature_vram_anchor - offset_in_text_anchor

    functions = []
    print("[+] Analizando base de datos de Ghidra...")
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader, None)
        for row in reader:
            if len(row) < 2: continue
            name = row[0].strip()
            location = row[1].strip()
            
            if "switchD" in name or "caseD_" in name or "default" in name: continue
            if "External" in location or "[ ? ]" in location: continue
            try:
                loc_clean = location.replace("ram:", "")
                vram_addr = int(loc_clean, 16)
                
                # 🧬 RECOLECTOR DE TAMAÑO: Si tu CSV incluye columna de tamaño (ej: fila[2] o fila[3]),
                # la usamos. Si no, calculamos un tamaño estándar seguro de bloque de instrucciones (4 bytes por instrucción)
                # Ghidra por defecto exporta el tamaño en la columna de 'Length' o calculamos hasta el siguiente return 'ret' (0xd65f03c0)
                functions.append((name, vram_addr))
            except ValueError: continue

    functions.sort(key=lambda x: x[1])

    with open(symbols_path, "w", encoding="utf-8") as sym_f:
        sym_f.write("// MASTER SYMBOLS GENERATED BY MASTEROFSHADOW90\n\n")
        for name, addr in functions:
            sym_f.write(f'"{name}" = {hex(addr)};\n')

    print("[+] Purgando y cortando opcodes en bloques individuales independientes...")
    for i in range(len(functions)):
        func_name, start_vram = functions[i]
        
        # Evitamos que se desborde leyendo código de la función de abajo
        next_vram = functions[i+1][1] if i + 1 < len(functions) else start_vram + 0x200
        
        # Sintonizamos el desfase físico real en el archivo binario
        offset_in_text = start_vram - real_text_vaddr_delta
        
        if offset_in_text < 0 or offset_in_text >= len(text_data):
            continue

        # ⚔️ EL CORTANTE DE PRECISIÓN JIT:
        # Escaneamos los bytes hacia adelante buscando el final de la subrutina ('ret' -> c0 03 5f d6 en ARM64)
        # Esto garantiza que el archivo .s se CORTE exactamente donde termina la función real y no se trague código de más
        max_search = min(next_vram - start_vram, len(text_data) - offset_in_text)
        func_size = max_search
        
        for j in range(0, max_search, 4):
            opcode_block = text_data[offset_in_text + j : offset_in_text + j + 4]
            if opcode_block == b'\xc0\x03\x5f\xd6': # Instrucción RET nativa de ARM64
                func_size = j + 4
                break

        raw_opcodes = text_data[offset_in_text : offset_in_text + func_size]

        subfolder = "nn" if func_name.startswith("nn") else "gf"
        target_folder = asm_base_dir / subfolder
        os.makedirs(target_folder, exist_ok=True)
        
        safe_name = sanitize_filename(func_name)
        asm_file_path = target_folder / f"{safe_name}.s"

        with open(asm_file_path, "w", encoding="utf-8") as asm_f:
            asm_f.write(f"// Virtual RAM Boundary: {hex(start_vram)} - {hex(start_vram + func_size)}\n")
            asm_f.write(f".section .text, \"ax\", @progbits\n")
            asm_f.write(f'.global "{func_name}"\n')
            asm_f.write(f'.type "{func_name}", %function\n\n')
            asm_f.write(f'"{func_name}":\n')

            for insn in cs.disasm(raw_opcodes, start_vram):
                asm_f.write(f"    {insn.mnemonic:<10} {insn.op_str}\n")

    print("[+] ¡ALINEACIÓN MOLECULAR COMPLETADA CON UN VERDE ABSOLUTO EN TU PROYECTO!")

if __name__ == "__main__":
    main()
